apiVersion: v1
kind: Pod
metadata:
  name: bandit
  labels:
    app: security-pipeline
spec:
  containers:
    - name: bandit
      image: xebiasecurity/bandit-defectdojo
      env: 
      - name: SOURCE_REPO #Get from vault 
        valueFrom:
          secretKeyRef:
            name: bandit-secrets
            key: repository #Get from vault
      - name: DOJO_API_KEY
        valueFrom:
          secretKeyRef:
            name: bandit-secrets
            key: dojo-api-key #Get from vault
      - name: DOJO_URL
        valueFrom:
          secretKeyRef:
            name: bandit-secrets
            key: dojo-url #Get as a secret
      - name: DOJO_ENGAGEMENT_ID
        valueFrom:
          secretKeyRef:
            name: bandit-secrets
            key: dojo-engagement-id #Get as a secret    
  restartPolicy: Never
