apiVersion: v1
kind: Pod
metadata:
  name: nmap
  labels:
    app: security-pipeline
spec:
  containers:
    - name: nmap
      image: rtencatexebia/nmap-scan
      env: 
      - name: IP #Get from vault 
        valueFrom:
          secretKeyRef:
            name: nmap-secrets
            key: ip-address #Get from vault
      - name: DOJO_API_KEY
        valueFrom:
          secretKeyRef:
            name: nmap-secrets
            key: dojo-api-key #Get from vault
      - name: DOJO_URL
        valueFrom:
          secretKeyRef:
            name: nmap-secrets
            key: dojo-url #Get as a secret
      - name: DOJO_ENGAGEMENT_ID
        valueFrom:
          secretKeyRef:
            name: nmap-secrets
            key: dojo-engagement-id #Get as a secret    
  restartPolicy: Never
